
Задания 3-5
```{r}
library(igraph)
path = "~/shared/minor2_2022/data/mid2-1/"
data = read.csv(paste0(path,"rfid.csv"))

g = graph.data.frame(data, directed = F)
g
plot(g)


sort(betweenness(g), decreasing = T)[1]
```

Задания 6-8
```{r}
set.seed(729)
walktrap.community(g)
membership(walktrap.community(g))["15"]
sizes(walktrap.community(g))
```


Задание 9
```{r}
library(igraph)
path = "~/shared/minor2_2022/data/mid2-1/"
data = read.csv(paste0(path,"rfid.csv"))
path = "~/shared/minor2_2022/data/mid2-1/"
attr = read.csv(paste0(path,"attr_rfid.csv"))

gf = graph_from_data_frame(data, directed = F, vertices = attr)
V(gf)$status = as.factor(V(gf)$status)
V(gf)$status

assortativity_nominal(gf, V(gf)$status, directed = F)
```

Задание 10
```{r}

number_of_permutations = 500
assortativity_shuffled  <- rep(NA, number_of_permutations)
set.seed(729)
for(i in 1:number_of_permutations){
  V(gf)$attr_shuffled = sample(V(gf)$status, replace = F)
  assortativity_shuffled[i] = assortativity_nominal(gf, V(gf)$attr_shuffled, directed = F)
}

q <- quantile(assortativity_shuffled, c(0.05, 0.95))
q

assortativity_real = assortativity_nominal(gf, V(gf)$status, directed = F)
assortativity_real

pvalue = sum(assortativity_shuffled <= assortativity_real) / number_of_permutations
pvalue
```

Задание 12
```{r}
library(igraph)

path = "~/shared/minor2_2022/data/mid2-1/"
friend = read.csv(paste0(path,"rfid_friend.csv"))


lst <- list(as_adjacency_matrix(gf, sparse = FALSE), as_adjacency_matrix(graph.data.frame(friend), sparse = FALSE))


detach("package:igraph")
library(sna)
set.seed(729)
qap <- qaptest(lst, gcor, g1=1, g2=2, reps=500)
summary(qap)
```

```{r}
detach("package:sna")
library(igraph)

library(ggraph)
gf_tbl = gf %>% as_tbl_graph()
gf_tbl %>% 
  mutate(betweenness = centrality_betweenness()) %>% 
  mutate(important = case_when(
      betweenness > quantile(betweenness, 0.75) ~ TRUE,
      TRUE ~ FALSE
    )) %>% 
ggraph() +
    geom_edge_link(color = "darkgray", width = 0.3, end_cap = circle(3, 'mm'), alpha = 0.6,
                   arrow = arrow(angle = 15, type = "closed", length = unit(3, 'mm'))) + 
    geom_node_point(aes(size = betweenness), color = "lightblue") + 
    geom_node_text(aes(label=name,
                       alpha = important), size = 2.5, show.legend = FALSE)  +
  theme_void()
```

Задание 14
```{r}
library(igraph)
path = "~/shared/minor2_2022/data/mid2-1/"
comics = read.csv(paste0(path,"comics45.csv"))


comicsnames = comics$comics
comics = comics %>% select(-comics) %>% as.matrix()
rownames(comics) = comicsnames

g <- graph_from_incidence_matrix(comics)
g

is.bipartite(g)
pr = bipartite.projection(g) 
p <- pr[[2]]
p

mean(E(p)$weight)

max(E(p)$weight)
```








